# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Ben/Desktop/HardwareProject2/registerFile/registerFile.cache/wt [current_project]
set_property parent.project_path C:/Users/Ben/Desktop/HardwareProject2/registerFile/registerFile.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib C:/Users/Ben/Desktop/HardwareProject2/project_tutorial/project_tutorial.srcs/sim_1/new/32bit_adder.vhd
synth_design -top thirtytwobit_adder -part xc7a35tcpg236-1
write_checkpoint -noxdef thirtytwobit_adder.dcp
catch { report_utilization -file thirtytwobit_adder_utilization_synth.rpt -pb thirtytwobit_adder_utilization_synth.pb }
