# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Yatagarasu/memoryUnit/memoryUnit.cache/wt [current_project]
set_property parent.project_path C:/Users/Yatagarasu/memoryUnit/memoryUnit.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib C:/Users/Yatagarasu/memoryUnit/memoryUnit.srcs/sources_1/new/memoryUnit.vhd
synth_design -top memoryUnit -part xc7a35tcpg236-1
write_checkpoint -noxdef memoryUnit.dcp
catch { report_utilization -file memoryUnit_utilization_synth.rpt -pb memoryUnit_utilization_synth.pb }
